export const UNKNOWN_TERMINAL_WIDTH = null;

// Cached one-shot tput fallback. We only call `tput cols` once because
// spawning a subprocess on every ~300ms statusline tick is too expensive.
// In normal operation env.COLUMNS is already set by the bash wrapper
// generated by /claude-hud:setup — this fallback only kicks in when the
// HUD is invoked manually (e.g. `node dist/index.js`) without the wrapper.
let _tputCols: number | null | undefined;

function tryTputCols(): number | null {
  if (_tputCols !== undefined) return _tputCols;
  _tputCols = null; // mark attempted, even on failure
  try {
    // require() is lazy — child_process is only loaded on the first miss
    const { execSync } = require("child_process") as typeof import("child_process");
    const raw = execSync("tput cols 2>/dev/null || echo ''", {
      encoding: "utf8",
      timeout: 500,
      stdio: ["ignore", "pipe", "ignore"],
    }).trim();
    if (raw) {
      const cols = parseInt(raw, 10);
      if (cols > 0) _tputCols = cols;
    }
  } catch {
    // tput not available (e.g. Windows PowerShell without Git Bash) —
    // leave _tputCols as null so we don't retry.
  }
  return _tputCols;
}

export function getTerminalWidth(): number | null {
  const { env, stdout, stderr } = process;

  // 1. COLUMNS env var: set by the statusLine bash wrapper generated by
  //    /claude-hud:setup. The wrapper uses `tput cols` (macOS, Linux,
  //    Windows Git Bash) or a PowerShell multi-method chain (Windows PS).
  //    See commands/setup.md step 1 for the full rationale.
  if (env.COLUMNS) {
    const cols = parseInt(env.COLUMNS, 10);
    if (cols > 0) return cols;
  }

  // 2. Node.js stream columns (available when stdout/stderr is a TTY)
  if (stdout?.columns) return stdout.columns;
  if (stderr?.columns) return stderr.columns;

  // 3. tput cols — one-shot subprocess fallback, cached after first call.
  //    Works reliably on Git Bash (Windows) and all Unix systems. Does
  //    NOT work on Windows PowerShell / cmd.exe (tput is not available),
  //    which is fine — those environments use the PowerShell wrapper.
  const tput = tryTputCols();
  if (tput !== null) return tput;

  return null;
}

export function getAdaptiveBarWidth(): number {
  const cols = getTerminalWidth();

  if (cols !== null) {
    if (cols >= 100) return 10;
    if (cols >= 60) return 6;
    return 4;
  }
  return 10;
}
