export const UNKNOWN_TERMINAL_WIDTH = null;

export function getTerminalWidth(): number | null {
  const { env, stdout, stderr } = process;

  // COLUMNS env var: set by the statusLine bash wrapper generated by
  // /claude-hud:setup. The wrapper uses a three-tier fallback (stty →
  // tput → 120) because stdout/stderr are piped in the subprocess and
  // Node.js reports their .columns as undefined. See commands/setup.md
  // step 1.5 for the full rationale.
  if (env.COLUMNS) {
    const cols = parseInt(env.COLUMNS, 10);
    if (cols > 0) return cols;
  }

  if (stdout?.columns) return stdout.columns;
  if (stderr?.columns) return stderr.columns;

  return null;
}

export function getAdaptiveBarWidth(): number {
  const cols = getTerminalWidth();

  if (cols !== null) {
    if (cols >= 100) return 10;
    if (cols >= 60) return 6;
    return 4;
  }
  return 10;
}
